version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: job_rec
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  airflow-webserver:
    image: apache/airflow:2.7.0

volumes:
  postgres_data:
